### ISSUE TITLE
Error: unkown read length

### ISSUE THREAD

**Issue by ViriatoII** [BGI-Qingdao/stlfr2supernova_pipeline#1]
Dear BGI,

I sent an email but maybe it makes sense having an issue here.  When running stlfr2supernova/run.sh, I get this error with your pipeline (in the split_barcode__10_30_23_45_27.log file) :

>Step 1: Loading barcodes ...
Barcode_types: 1536 X 1536 X 1536 = 3623878656
Step 1 : Done
Step 2 : Check r2 length and barcode stype ...
Unknow read length of r2:100.
Please check the tmp_r2.fq.gz file!

What is happening?

Thank you,
Ricardo

**Comment by cchd0001** [comment]
Hi Ricardo , 

The read length of raw stLFR  read2 is always greater than 100 bp.  Given the read length of read2 of your input is 100 bp, I assume that your inputs are either normal NGS or processed stLFR reads.
    
Please check the read-name line ( first line ) of your fastq. If the format follows @xxxx#123_234_345/1 pattern then your inputs are processed stLFR reads, and there is no need to process them again. Please follow the instruction [here ](https://github.com/BGI-Qingdao/stlfr2supernova_pipeline#start-from-stlfr-reads-which-already-split-barcode) to skip this step and continue others.
    
 Tips : 

1. This pipeline have 4 steps :   **a**) process barcodes; **b**)  quality control; **c**) convert format to 10x; **d**) assembly by supernova.     
2. If the read file names are "split_reads.1.fq.gz"  and "split_reads.2.fq.gz" , then they are stLFR reads whose barcodes have been already  processed ( refer to step **a** done ). 
3. If the read file names follow above pattern but also contain "clean"  or "cleaned" ,  they are stLFR clean reads with  processed barcodes after quality control. ( refer to step **a** and **b** done ). 

Best wishes
Lidong Guo

**Comment by ViriatoII** [comment]
Dear Guo,

I wasn't 100% sure, but my reads are cleaned already, they are called: "clean_read_1.fq.gz".  That means I have step a) and b) done.

I followed your instructions and it worked, thank you.

``` 
gzip -dc clean_read_1.fq.gz |  awk -F '#|/' '{if(NR%4==1&&NF>1)t[$2]+=1}END{for(x in t ) printf("%s\t%s\n",x,t[x]);}' > barcode_freq.txt 

ln -s clean_read_1.fq.gz  split_reads.1.fq.gz.clean.gz
ln -s clean_read_2.fq.gz  split_reads.2.fq.gz.clean.gz
	
touch _step_0_end.txt # to avoid split reads step
touch _step_1_end.txt # to avoid SOAPfilter step

	
/....../src/stlfr2supernova/run.sh
```

Kind regards,
Ricardo
