### ISSUE TITLE
示例文件报错

### ISSUE THREAD

**Issue by fys666** [BGI-Qingdao/stlfr2supernova_pipeline#4]
你好，我使用示例文件测试时遇到了错误

我输入的文件是https://github.com/BGI-Qingdao/stlfr2supernova_pipeline里的两个。Appendix B : an example of stLFR reads

这是我的运行命令
python3 /software/de_nova_pipeline/stlfr2supernova/clean_stLFR_data2supernova/clean_stlfr2supernova_pipline.py -r1 testdata/test_stlfr_1.fq.gz -r2 testdata/test_stlfr_2.fq.gz -supernova /software/de_nova_pipeline/supernova-2.1.1/ -s /software/de_nova_pipeline/stlfr2supernova/clean_stLFR_data2supernova/ -o log_out -M 256 -t 32

我的日志文件和测试文件在这个网盘里
https://cowtransfer.com/s/6276ae60126846 点击链接查看 [ pipeline_all.tar.gz ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 9rwa6v 查看；

请帮助查看，谢谢

**Comment by Ethan-Fu-2000** [comment]
> 你好，我使用示例文件测试时遇到了错误
> 
> 我输入的文件是[https://github.com/BGI-Qingdao/stlfr2supernova_pipeline里的两个。Appendix](https://github.com/BGI-Qingdao/stlfr2supernova_pipeline%E9%87%8C%E7%9A%84%E4%B8%A4%E4%B8%AA%E3%80%82Appendix) B : an example of stLFR reads
> 
> 这是我的运行命令 python3 /software/de_nova_pipeline/stlfr2supernova/clean_stLFR_data2supernova/clean_stlfr2supernova_pipline.py -r1 testdata/test_stlfr_1.fq.gz -r2 testdata/test_stlfr_2.fq.gz -supernova /software/de_nova_pipeline/supernova-2.1.1/ -s /software/de_nova_pipeline/stlfr2supernova/clean_stLFR_data2supernova/ -o log_out -M 256 -t 32python3 /software/de_nova_pipeline/stlfr2supernova/clean_stLFR_data2supernova/clean_stlfr2supernova_pipline.py -r1 testdata/test_stlfr_1.fq.gz -r2 testdata/test_stlfr_2.fq.gz -supernova /software/de_nova_pipeline/supernova-2.1.1/ -s /software/ de_nova_pipeline /stlfr2supernova/clean_stLFR_data2supernova/ -o log_out -M 256 -t 32
> 
> 我的日志文件和测试文件在这个网盘里 https://cowtransfer.com/s/6276ae60126846 点击链接查看 [ pipeline_all.tar.gz ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 9rwa6v 查看；
> 
> 请帮助查看，谢谢

另外我发现sample_S1_L001_xx_001.fastq.gz 这三个文件都是空的

**Comment by cchd0001** [comment]
README中的仅仅用来说明数据格式，请用真实数据测试

README中的数据reads数目太少，会全部被filter掉，也不可能产出有效的组装结果

**Comment by Ethan-Fu-2000** [comment]
> README中的仅仅用来说明数据格式，请用真实数据测试
> 
> README中的数据reads数目太少，会全部被filter掉，也不可能产出有效的组装结果

那请问#123_234_345/1  这样的fastq可以吗？还是必须要是#123_234_345/1 1 1 这样的，我的已经是过滤后的fastq
![image](https://github.com/BGI-Qingdao/stlfr2supernova_pipeline/assets/55824187/9f865abe-04ad-40a4-b0f8-3c041e9648bc)

**Comment by Ethan-Fu-2000** [comment]
> > README中的仅仅用来说明数据格式，请用真实数据测试
> > README中的数据reads数目太少，会全部被filter掉，也不可能产出有效的组装结果
> 
> 那请问#123_234_345/1 这样的fastq可以吗？还是必须要是#123_234_345/1 1 1 这样的，我的已经是过滤后的fastq ![image](https://user-images.githubusercontent.com/55824187/273424536-9f865abe-04ad-40a4-b0f8-3c041e9648bc.png)

最后一个数字1是barcode的频率吗

**Comment by cchd0001** [comment]
> > > README中的仅仅用来说明数据格式，请用真实数据测试
> > > README中的数据reads数目太少，会全部被filter掉，也不可能产出有效的组装结果
> > 
> > 
> > 那请问#123_234_345/1 这样的fastq可以吗？还是必须要是#123_234_345/1 1 1 这样的，我的已经是过滤后的fastq ![image](https://user-images.githubusercontent.com/55824187/273424536-9f865abe-04ad-40a4-b0f8-3c041e9648bc.png)
> 
> 最后一个数字1是barcode的频率吗

#123_234_345/1 就好
